### PR TITLE
Sort authors with equal commit count by name

### PR DESCRIPTION
**Pull request by vweevers**
To get a stable sort order, e.g. when you have many one-of contributors with a single commit.

### CODE REVIEW

**Review by ChristianMurphy — APPROVED** [review]

**Review by wooorm — APPROVED** [review]

**Comment by wooorm** [comment]
Whoops, this hasn’t been released. I think this should be a major as the sorting changes?

**Comment by vweevers** [comment]
I consider it a fix.

**Comment by wooorm** [comment]
Hmm I guess there's a slim chance that it changes something...

**Comment by vweevers** [comment]
Before this, you'd get a different sort order between e.g. node versions. That's a bug. Yes, in some cases this will change the order of ~~commits~~ authors. Why do you consider that breaking?

**Comment by wooorm** [comment]
I think semver is confusing here because it defines two axes: change, feature, patch, but also compatible, incompatible, incompatible. I see any changes to side effects (input/output) as incompatible.

**Comment by wooorm** [comment]
Released as a patch

**Comment by vweevers** [comment]
Thanks!

FWIW, my point of view is that making the sort order stable fixes more incompatibilities (between node versions, as well as between runs depending on node version) than it introduces. For that reason, I want to deliver the fix to consumers automatically, by floating it in as semver-patch.

And, if we make semver-major releases for trivial reasons, on the long term we reduce the value of the semver-major signal. Which is, "this release requires extra attention". If your smoke alarm keeps going off, but it's a false positive every time, eventually you'll take out the battery.

**Comment by wooorm** [comment]
That is indeed an interesting trade off, but it doesn’t calculate in broken builds and the harm that does to the JavaScript/Node/npm ecosystem.

> If your smoke alarm keeps going off, but it's a false positive every time, eventually you'll take out the battery.

It’s not a false positive. There is a fire.

**Pull request merged**
